/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatorialclasse02;

/**
 *
 * @author PC
 */
public class TelaFatorialClasse02Swing extends javax.swing.JFrame {

    /**
     * Creates new form TelaFatorialClasse02Swing
     */
    public TelaFatorialClasse02Swing() {
        initComponents();
        jpainelResultado.setVisible(false);
        jlbl5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspinNumero = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jbtnCalcular = new javax.swing.JButton();
        jpainelResultado = new javax.swing.JPanel();
        jlblFormula = new javax.swing.JLabel();
        jlblResultado = new javax.swing.JLabel();
        jlbl5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jspinNumero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jspinNumero.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fatorial.gif"))); // NOI18N

        jbtnCalcular.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jbtnCalcular.setText("!");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jpainelResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlblFormula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblFormula.setText("Formula");

        jlblResultado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblResultado.setText("Resultado");

        jlbl5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbl5.setText("==5");

        javax.swing.GroupLayout jpainelResultadoLayout = new javax.swing.GroupLayout(jpainelResultado);
        jpainelResultado.setLayout(jpainelResultadoLayout);
        jpainelResultadoLayout.setHorizontalGroup(
            jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainelResultadoLayout.createSequentialGroup()
                .addGroup(jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpainelResultadoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jlblFormula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblResultado))
                    .addGroup(jpainelResultadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbl5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpainelResultadoLayout.setVerticalGroup(
            jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainelResultadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFormula)
                    .addComponent(jlblResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Calculo Fatorial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jspinNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2)))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(jpainelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jspinNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCalcular))
                .addGap(12, 12, 12)
                .addComponent(jpainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        jpainelResultado.setVisible(true);
        int nume = Integer.parseInt(jspinNumero.getValue().toString());
        Fatorial fat = new Fatorial();
        fat.valor(nume);
        jlblFormula.setText(fat.mostraFormula());
        jlblResultado.setText(Integer.toString(fat.mostraFactorial()));
        
        if (nume==5){
            jlbl5.setVisible(true);
            jlbl5.setText("Tente outro Número Além do que esta no gif seu prequiçoso");
            
        }else{
            jlbl5.setVisible(false);
        }
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFatorialClasse02Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFatorialClasse02Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFatorialClasse02Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFatorialClasse02Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFatorialClasse02Swing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JLabel jlbl5;
    private javax.swing.JLabel jlblFormula;
    private javax.swing.JLabel jlblResultado;
    private javax.swing.JPanel jpainelResultado;
    private javax.swing.JSpinner jspinNumero;
    // End of variables declaration//GEN-END:variables
}
