/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vetorswing;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author PC
 */
public class TelaVetor extends javax.swing.JFrame {
    
    int valores[] = new int[5];
    DefaultListModel list = new DefaultListModel();
    int select = 0;

    /**
     * Creates new form TelaVetor
     */
    public TelaVetor() {
        initComponents();
         for(int contador = 0; contador<valores.length; contador++){
            list.addElement(valores[contador]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspinNumeros = new javax.swing.JSpinner();
        jbtnAdd = new javax.swing.JButton();
        jbtnRemo = new javax.swing.JButton();
        jbtnOrdem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistVetores = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jlblPos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jbtnAdd.setText("Adicionar");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnRemo.setText("Remover");
        jbtnRemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoActionPerformed(evt);
            }
        });

        jbtnOrdem.setText("Ordenar");
        jbtnOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrdemActionPerformed(evt);
            }
        });

        jlistVetores.setModel(list);
        jlistVetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistVetoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlistVetores);

        jLabel1.setText("Vetor");

        jlblPos.setText("[0]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jspinNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAdd)
                    .addComponent(jbtnOrdem)
                    .addComponent(jbtnRemo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPos)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAdd)
                            .addComponent(jspinNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnOrdem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlblPos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        valores[select] = Integer.parseInt(jspinNumeros.getValue().toString());
        list.removeAllElements();
        for(int contador = 0; contador<valores.length; contador++){
            list.addElement(valores[contador]);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jlistVetoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistVetoresMouseClicked
        // TODO add your handling code here:
        select = jlistVetores.getSelectedIndex();
        jlblPos.setText("("+(select+1)+")");
    }//GEN-LAST:event_jlistVetoresMouseClicked

    private void jbtnRemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoActionPerformed
        // TODO add your handling code here:
        valores[select] = 0;
        list.removeAllElements();
         for(int contador = 0; contador<valores.length; contador++){
            list.addElement(valores[contador]);
        }
    }//GEN-LAST:event_jbtnRemoActionPerformed

    private void jbtnOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrdemActionPerformed
        // TODO add your handling code here:
        Arrays.sort(valores);
        list.removeAllElements();
         for(int contador = 0; contador<valores.length; contador++){
            list.addElement(valores[contador]);
        }
    }//GEN-LAST:event_jbtnOrdemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnOrdem;
    private javax.swing.JButton jbtnRemo;
    private javax.swing.JLabel jlblPos;
    private javax.swing.JList<String> jlistVetores;
    private javax.swing.JSpinner jspinNumeros;
    // End of variables declaration//GEN-END:variables
}
