/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package votacao;

import java.time.YearMonth;

/**
 *
 * @author PC
 */
public class TelaVotacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaVotacao
     */
    public TelaVotacao() {
        initComponents();
        jlblResultado.setVisible(false);
        jlblIdade.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnCalcular = new javax.swing.JButton();
        jlblResultado = new javax.swing.JLabel();
        jtxtAnoNascimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlblIdade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ano Nascimento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jbtnCalcular.setText("Eu Voto?");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jlblResultado.setText("0");
        getContentPane().add(jlblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 115, -1));
        getContentPane().add(jtxtAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 250, 10));

        jlblIdade.setText("0");
        getContentPane().add(jlblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        jlblResultado.setVisible(true);
        jlblIdade.setVisible(true);
        int anoAtual = YearMonth.now().getYear();
        int anoNascimento = Integer.parseInt(jtxtAnoNascimento.getText());
        int idade = anoAtual - anoNascimento;
        jlblIdade.setText("Sua Idade è " + idade);
        if(idade<16){
            jlblResultado.setText("Não Vota");
        }else{
            if((idade>16 & idade<18)|(idade>70)){
                jlblResultado.setText("O Voto é Opcional");
            }else{
                jlblResultado.setText("O Voto é Obrigatorio");
            }
        }
        
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVotacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JLabel jlblIdade;
    private javax.swing.JLabel jlblResultado;
    private javax.swing.JTextField jtxtAnoNascimento;
    // End of variables declaration//GEN-END:variables
}
