/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package triangulos;

/**
 *
 * @author PC
 */
public class TelaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulo
     */
    public TelaTriangulo() {
        initComponents();
        jpainelResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsliA = new javax.swing.JSlider();
        jsliB = new javax.swing.JSlider();
        jsliC = new javax.swing.JSlider();
        jlblA = new javax.swing.JLabel();
        jlblB = new javax.swing.JLabel();
        jlblC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnVerificar = new javax.swing.JButton();
        jpainelResultado = new javax.swing.JPanel();
        jlblForma = new javax.swing.JLabel();
        jlblTriangulos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Segmento A");

        jLabel2.setText("Segmento B");

        jLabel3.setText("Segmento C");

        jsliA.setMaximum(20);
        jsliA.setValue(0);
        jsliA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsliAStateChanged(evt);
            }
        });

        jsliB.setMaximum(20);
        jsliB.setValue(0);
        jsliB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsliBStateChanged(evt);
            }
        });

        jsliC.setMaximum(20);
        jsliC.setValue(0);
        jsliC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsliCStateChanged(evt);
            }
        });

        jlblA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlblA.setText("0");

        jlblB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlblB.setText("0");

        jlblC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlblC.setText("0");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Screenshot_1.png"))); // NOI18N

        jbtnVerificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbtnVerificar.setText("Verificar");
        jbtnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerificarActionPerformed(evt);
            }
        });

        jlblForma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblForma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblForma.setText("Forma ou não");
        jlblForma.setToolTipText("");

        jlblTriangulos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTriangulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTriangulos.setText("Tipos de Triangulos");
        jlblTriangulos.setToolTipText("");

        javax.swing.GroupLayout jpainelResultadoLayout = new javax.swing.GroupLayout(jpainelResultado);
        jpainelResultado.setLayout(jpainelResultadoLayout);
        jpainelResultadoLayout.setHorizontalGroup(
            jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainelResultadoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblForma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTriangulos, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpainelResultadoLayout.setVerticalGroup(
            jpainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainelResultadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlblForma)
                .addGap(18, 18, 18)
                .addComponent(jlblTriangulos)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsliC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsliB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsliA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblA))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jbtnVerificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jpainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jsliA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jsliB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblB))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jsliC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblC))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnVerificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerificarActionPerformed
        // TODO add your handling code here:
        jpainelResultado.setVisible(true);
        int a = jsliA.getValue();
        int b = jsliB.getValue();
        int c = jsliC.getValue();
        if(a<b+c && b<a+c && c<a+b){
            jlblForma.setText("Formam um Triângulo");
            if(a==b && b==c){
                jlblTriangulos.setText("Equilátero");
            }else if(a!=b && b!=c && c!=a){
                jlblTriangulos.setText("Escaleno");
            }else{
                jlblTriangulos.setText("Isósceles");
            }
        }else{
            jlblForma.setText("Não Formam um Triângulo");
            jlblTriangulos.setText("_");
        }
        
    }//GEN-LAST:event_jbtnVerificarActionPerformed

    private void jsliAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsliAStateChanged
        // TODO add your handling code here:
        jlblA.setText(Integer.toString(jsliA.getValue()));
    }//GEN-LAST:event_jsliAStateChanged

    private void jsliBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsliBStateChanged
        // TODO add your handling code here:
        jlblB.setText(Integer.toString(jsliB.getValue()));
    }//GEN-LAST:event_jsliBStateChanged

    private void jsliCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsliCStateChanged
        // TODO add your handling code here:
        jlblC.setText(Integer.toString(jsliC.getValue()));
    }//GEN-LAST:event_jsliCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnVerificar;
    private javax.swing.JLabel jlblA;
    private javax.swing.JLabel jlblB;
    private javax.swing.JLabel jlblC;
    private javax.swing.JLabel jlblForma;
    private javax.swing.JLabel jlblTriangulos;
    private javax.swing.JPanel jpainelResultado;
    private javax.swing.JSlider jsliA;
    private javax.swing.JSlider jsliB;
    private javax.swing.JSlider jsliC;
    // End of variables declaration//GEN-END:variables
}
